package com.emz.protec.seed;

import java.util.List;

final class CatalogSeedData {

	private CatalogSeedData() {
	}

	static List<String> categories() {
		return List.of(
				"Cámaras IP",
				"Cámaras analógicas",
				"Cámaras PTZ",
				"DVR / NVR",
				"Almacenamiento",
				"Cableado y red",
				"Alimentación",
				"Monitores",
				"Alarmas",
				"Control de acceso",
				"Kits",
				"Accesorios");
	}

	static List<SeedProduct> products() {
		return List.of(
				p("Cámara Domo IP 4K Full Color", "Cámaras IP", "899.90",
						"4K, visión nocturna a color, PoE, IP67, micrófono integrado"),
				p("Cámara Bullet IP 5MP IR 40m", "Cámaras IP", "549.50",
						"5MP, IR 40m, lente 3.6mm, carcasa metálica, IP67"),
				p("Cámara Domo IP 8MP WDR", "Cámaras IP", "729.00",
						"8MP, WDR 120dB, H.265+, PoE, ranura microSD"),
				p("Cámara Mini Domo IP 2MP", "Cámaras IP", "289.00",
						"2MP, interior, PoE, ángulo 2.8mm, compacta"),
				p("Cámara Bullet IP 4MP ColorVu", "Cámaras IP", "619.00",
						"4MP, Full-Color 24/7, luz cálida, micrófono, IP67"),
				p("Cámara Turret IP 5MP AcuSense", "Cámaras IP", "799.00",
						"5MP, detección de personas/vehículos, IR 30m, PoE"),
				p("Cámara WiFi Domo 3MP", "Cámaras IP", "349.00",
						"3MP, WiFi 2.4GHz, audio bidireccional, cloud opcional"),
				p("Cámara Fisheye IP 6MP 360°", "Cámaras IP", "1299.00",
						"6MP, 360°, dewarping, PoE, techo interior"),
				p("Cámara Bullet IP 8MP 4K IR 80m", "Cámaras IP", "1149.00",
						"8MP 4K, IR 80m, lente 2.8-12mm, IP67, IK10"),
				p("Cámara Mini Bullet IP 4MP", "Cámaras IP", "459.00",
						"4MP, IR 20m, PoE, compacta para residencial"),

				p("Cámara Domo analógica 2MP HD", "Cámaras analógicas", "159.00",
						"2MP 1080p, TVI/AHD/CVI/CVBS, IR 20m"),
				p("Cámara Bullet analógica 5MP IR", "Cámaras analógicas", "219.00",
						"5MP, IR 40m, 4 en 1, carcasa metálica"),
				p("Cámara Turret analógica 2MP", "Cámaras analógicas", "189.00",
						"2MP, lente 2.8mm, IR 30m, interior/exterior"),
				p("Cámara Bullet analógica 8MP", "Cámaras analógicas", "329.00",
						"8MP, 4 en 1, IR 60m, OSD, IP66"),
				p("Cámara Mini Domo analógica 2MP", "Cámaras analógicas", "129.00",
						"2MP, interior, plástico, IR 15m"),

				p("Cámara PTZ IP 2MP 20x", "Cámaras PTZ", "1899.00",
						"Zoom óptico 20x, tracking automático, PoE+, IR 150m"),
				p("Cámara PTZ IP 4MP 25x", "Cámaras PTZ", "2499.00",
						"4MP, zoom 25x, auto-tracking, wiper, IP66"),
				p("Cámara Speed Dome 2MP 30x", "Cámaras PTZ", "3199.00",
						"2MP, zoom 30x, preset 300, IR 200m, Hi-PoE"),
				p("Cámara PTZ WiFi 3MP", "Cámaras PTZ", "459.00",
						"3MP, pan/tilt, WiFi, audio, seguimiento humano"),
				p("Cámara PTZ Mini 4MP 4x", "Cámaras PTZ", "899.00",
						"4MP, zoom 4x, PoE, interior, tracking"),

				p("NVR 8 Canales 4K", "DVR / NVR", "1299.00",
						"8 canales IP, HDMI 4K, 2 bahías SATA, PoE opcional"),
				p("NVR 16 Canales 4K", "DVR / NVR", "1899.00",
						"16 canales IP, 4K, 4 SATA hasta 10TB c/u, RAID"),
				p("NVR 4 Canales PoE", "DVR / NVR", "799.00",
						"4 canales, 4 puertos PoE, 1 SATA, compacto"),
				p("NVR 32 Canales 8K", "DVR / NVR", "3499.00",
						"32 canales, salida 8K, 8 SATA, alarmas I/O"),
				p("DVR 8 Canales H.265 5MP", "DVR / NVR", "649.00",
						"8 canales analógicos/IP, H.265+, 1 SATA"),
				p("DVR 16 Canales H.265", "DVR / NVR", "999.00",
						"16 canales, H.265+, 2 SATA, HDMI/VGA"),
				p("DVR 4 Canales 1080p", "DVR / NVR", "429.00",
						"4 canales, 1080p, P2P, 1 SATA"),
				p("XVRhybrid 8 Canales 8MP", "DVR / NVR", "879.00",
						"Híbrido TVI/AHD/IP, 8MP, 2 SATA"),

				p("Disco Duro Vigilancia 1TB", "Almacenamiento", "189.00",
						"HDD 1TB 5400rpm, especial CCTV 24/7"),
				p("Disco Duro Vigilancia 2TB", "Almacenamiento", "279.00",
						"HDD 2TB, cache 64MB, vigilancia 24/7"),
				p("Disco Duro Vigilancia 4TB", "Almacenamiento", "429.00",
						"HDD 4TB 5400rpm, optimizado para NVR/DVR"),
				p("Disco Duro Vigilancia 6TB", "Almacenamiento", "619.00",
						"HDD 6TB, alta durabilidad, 3 años garantía"),
				p("Disco Duro Vigilancia 8TB", "Almacenamiento", "849.00",
						"HDD 8TB, 7200rpm, RAID compatible"),
				p("SSD 256GB para NVR", "Almacenamiento", "159.00",
						"SSD SATA 256GB, sistema/OS del grabador"),
				p("MicroSD 128GB Vigilancia", "Almacenamiento", "79.00",
						"microSDXC 128GB, alta resistencia de escritura"),
				p("MicroSD 256GB Endurance", "Almacenamiento", "139.00",
						"256GB endurance, cámaras con slot SD"),

				p("Kit Cable UTP Cat6 305m", "Cableado y red", "259.00",
						"Bobina Cat6 CCA 305m, exterior, negro"),
				p("Kit Cable UTP Cat5e 305m", "Cableado y red", "189.00",
						"Bobina Cat5e 305m, interior, azul"),
				p("Cable coaxial RG59 + power 100m", "Cableado y red", "149.00",
						"RG59 + 2x18AWG, 100 metros, siameses"),
				p("Switch PoE 8 puertos Fast", "Cableado y red", "319.90",
						"8 puertos PoE Fast Ethernet, 120W, no administrable"),
				p("Switch PoE 16 puertos Gigabit", "Cableado y red", "899.00",
						"16 PoE+ Gigabit, 250W, uplink 2 SFP"),
				p("Switch PoE 4 puertos", "Cableado y red", "179.00",
						"4 PoE + 2 uplink, 60W, compacto"),
				p("Router 4G para CCTV", "Cableado y red", "389.00",
						"4G LTE, 4 LAN, VPN, backup de internet"),
				p("Conectores RJ45 Cat6 x100", "Cableado y red", "45.00",
						"Pack 100 conectores RJ45 Cat6, chapado oro"),
				p("Jack RJ45 hembra x20", "Cableado y red", "59.00",
						"Keystone Cat6, pack 20 unidades"),

				p("Fuente 12V 5A caja metálica", "Alimentación", "89.00",
						"12V 5A, 4 salidas, protección contra corto"),
				p("Fuente 12V 10A 9 cámaras", "Alimentación", "129.00",
						"12V 10A, 9 canales, fusibles individuales"),
				p("Fuente 12V 20A 18 canales", "Alimentación", "199.00",
						"12V 20A, 18 salidas, rack/caja metálica"),
				p("Inyector PoE Gigabit 30W", "Alimentación", "79.00",
						"PoE 802.3af/at, 30W, 10/100/1000"),
				p("UPS 1kVA para NVR", "Alimentación", "459.00",
						"1kVA / 600W, 15-20 min autonomía, AVR"),
				p("UPS 2kVA rack", "Alimentación", "899.00",
						"2kVA, rack 2U, para rack de CCTV"),

				p("Monitor LED 21.5\" HDMI", "Monitores", "449.00",
						"21.5\" Full HD, HDMI/VGA, 24/7 CCTV"),
				p("Monitor LED 27\" 4K", "Monitores", "899.00",
						"27\" 4K, HDMI 2.0, para NVR 4K"),
				p("Monitor 32\" videowall", "Monitores", "1299.00",
						"32\" industrial, 16/7, BNC/HDMI, metal"),
				p("Monitor 43\" 4K CCTV", "Monitores", "1699.00",
						"43\" 4K, HDMI/VGA, montaje VESA"),
				p("Soporte TV/monitor articulado", "Monitores", "89.00",
						"Brazo articulado 17-32\", VESA 100x100"),

				p("Alarma inalámbrica kit 4 zonas", "Alarmas", "399.00",
						"Panel WiFi/4G, 2 PIR, 1 magnético, 2 controles"),
				p("Panel de alarma 8 zonas", "Alarmas", "549.00",
						"8 zonas cableadas, app, batería backup"),
				p("Sensor PIR interior", "Alarmas", "49.00",
						"PIR pet-immune, 12m, 110°, 12V"),
				p("Sensor magnético puerta/ventana", "Alarmas", "19.00",
						"Contacto magnético NC, cableado"),
				p("Sirena exterior 120dB", "Alarmas", "89.00",
						"Sirena 120dB + strobe, 12V, IP54"),
				p("Teclado LCD alarma", "Alarmas", "159.00",
						"Teclado LCD, armado/desarmado, 12V"),

				p("Control de acceso 1 puerta TCP/IP", "Control de acceso", "699.00",
						"Huella + RFID + código, 3000 usuarios, TCP/IP"),
				p("Control de acceso facial 2MP", "Control de acceso", "1299.00",
						"Reconocimiento facial, RFID, WiFi, 5000 caras"),
				p("Cerradura electromagnética 280kg", "Control de acceso", "189.00",
						"Maglock 280kg, 12V, L/Z bracket incluido"),
				p("Cerradura electromagnética 600kg", "Control de acceso", "279.00",
						"Maglock 600kg, LED, sensor de puerta"),
				p("Lector RFID 125kHz", "Control de acceso", "79.00",
						"Lector Wiegand 26, IP65, 125kHz"),
				p("Tarjetas RFID pack x50", "Control de acceso", "59.00",
						"50 tarjetas EM 125kHz, imprimibles"),
				p("Botón de salida NO/NC", "Control de acceso", "25.00",
						"Botón inox, NO/NC, empotrar"),
				p("Fuente 12V para acceso + batería", "Control de acceso", "149.00",
						"12V 5A, cargador de batería 7Ah, backup"),

				p("Kit 4 cámaras IP 4MP + NVR PoE", "Kits", "1899.00",
						"NVR 4ch PoE, 4 bullets 4MP, 1TB, cables 20m"),
				p("Kit 8 cámaras IP 5MP + NVR", "Kits", "3299.00",
						"NVR 8ch PoE, 8 cámaras 5MP, HDD 2TB"),
				p("Kit 4 cámaras analógicas 2MP", "Kits", "899.00",
						"DVR 4ch, 4 bullets 2MP, fuente, 1TB"),
				p("Kit 16 cámaras IP 4MP empresa", "Kits", "7990.00",
						"NVR 16ch, 16 IP 4MP, switch PoE 16p, HDD 4TB"),
				p("Kit residencial WiFi 2 cámaras", "Kits", "649.00",
						"2 cámaras WiFi 3MP, NVR inalámbrico, app"),

				p("Caja estanca IP66 cámara", "Accesorios", "39.00",
						"Caja de conexiones IP66, para bullet"),
				p("Soporte pared cámara bullet", "Accesorios", "29.00",
						"Brazo de pared aluminio, 20cm"),
				p("Carcasa outdoor con calentador", "Accesorios", "159.00",
						"Housing IP66, blower + heater, 12V"),
				p("Balun pasivo 4K par", "Accesorios", "19.00",
						"Par baluns 4K por UTP, tornillo"),
				p("Rack 6U mural", "Accesorios", "329.00",
						"Gabinete 6U, 450mm, puerta vidrio"),
				p("Rack 12U mural", "Accesorios", "499.00",
						"Gabinete 12U, 550mm, ventilación"),
				p("Patch cord Cat6 1m x10", "Accesorios", "39.00",
						"10 patch cords Cat6 1 metro"),
				p("Tester de cable RJ45/BNC", "Accesorios", "69.00",
						"Probador UTP/coaxial, remoto"),
				p("Herramienta ponchadora RJ45", "Accesorios", "35.00",
						"Crimpadora RJ45/RJ11, pelacables"));
	}

	private static SeedProduct p(String name, String category, String price, String specs) {
		return new SeedProduct(name, category, price, specs);
	}

	record SeedProduct(String name, String category, String price, String specs) {
	}
}
